trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallAndBuild
  displayName: 'Install Dependencies and Build'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        checkLatest: true
    
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Install Client Dependencies and Build Frontend'

    - script: |
        npm install
      displayName: 'Install Backend Dependencies and Build Backend'
    


    - script: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
      displayName: 'Install Geckodriver'

    - script: |
        sudo apt-get update
        sudo apt-get install -y firefox
      displayName: 'Install Firefox'
  
    - script: |
        echo "Using Firefox from $(which firefox)"
      displayName: 'Check Firefox Path'


    - script: |
        npm start &
        sleep 5
        cd client
        npm run dev &
        sleep 5
      displayName: 'Both Frontend and Backend Running'

    - script: |
        cd client
        export DISPLAY=:99
        sudo Xvfb :99 -ac -screen 0 1280x1024x24 &
        npm run test
      env:
        FIREFOX_BIN: /usr/bin/firefox
      displayName: 'Run Selenium tests'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/client/dist'
        ArtifactName: 'frontend'
      displayName: 'Publish Frontend Build Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/api/node/dist'
        ArtifactName: 'backend'
      displayName: 'Publish Backend Build Artifacts'
