trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install
        npm run build
        cd ../api
        npm install
      displayName: 'Install dependencies and build client'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'client/dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/client_build'
      displayName: 'Copy client build to artifact staging directory'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'api'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/api'
      displayName: 'Copy API to artifact staging directory'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive build files'

    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop
      displayName: 'Publish build artifacts'

