trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallAndBuild
  displayName: 'Install Dependencies and Build'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        checkLatest: true

    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Install Client Dependencies and Build Frontend'

    - script: |
        npm install
      displayName: 'Install Backend Dependencies'

    - script: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
      displayName: 'Install Geckodriver'

    - script: |
        sudo apt-get update
        sudo apt-get install -y wget tar bzip2
        wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        tar -xjf firefox.tar.bz2
        sudo mv firefox /opt/firefox
        sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
        echo "Firefox installed at: $(which firefox)"
      displayName: 'Install Firefox'

    - script: |
        echo "Checking Firefox executable and permissions:"
        ls -l /usr/local/bin/firefox
        file /usr/local/bin/firefox
        sudo chmod +x /usr/local/bin/firefox
      displayName: 'Check Firefox Executable'

    - script: |
        npm start &
        sleep 5
        cd client
        npm run dev &
        sleep 5
      displayName: 'Both Frontend and Backend Running'

    - script: |
        cd client
        npm run test
      displayName: 'Run Selenium tests'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/client/dist'
        ArtifactName: 'frontend'
        publishLocation: 'container'
      displayName: 'Publish Frontend Build Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/api/node/dist'
        ArtifactName: 'backend'
        publishLocation: 'container'
      displayName: 'Publish Backend Build Artifacts'
