trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallAndBuild
  displayName: 'Install Dependencies and Build'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        checkLatest: true
    
    - script: |
        sudo apt-get update
        sudo apt-get install -y firefox
      displayName: 'Install Firefox'

    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Install Client Dependencies and Build Frontend'

    - script: |
        npm install
      displayName: 'Install Backend Dependencies and Build Backend'
    

    - script: |
        npm start &
        sleep 10
        cd client
        npm run dev &
        sleep 10
        npm test
      displayName: 'Run Tests with Both Frontend and Backend Running'


    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/client/dist'
        ArtifactName: 'frontend'
      displayName: 'Publish Frontend Build Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/api/node/dist'
        ArtifactName: 'backend'
      displayName: 'Publish Backend Build Artifacts'
